services:
  # 🚀 NATS
  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"

  # 🟢 Client gateway
  client-gateway:
    build: ./client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222

  # 🟡 Services
  auth-ms:
    build: ./auth-ms
    command: npm run start:dev
    environment:
      - PORT=3004
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=mongodb://root:123456@db-mongo-users:27017
    volumes:
      - ./auth-ms/src:/usr/src/app/src
    depends_on:
      - db-mongo-users

  products-ms:
    build: ./products-ms
    command: npm run start:dev
    environment:
      - PORT=3001
      - DATABASE_URL=file:./dev.db
      - NATS_SERVERS=nats://nats-server:4222
    volumes:
      - ./products-ms/src:/usr/src/app/src

  orders-ms:
    build: ./orders-ms
    restart: always
    command: npm run start:dev
    environment:
      - PORT=3002
      - DATABASE_URL=postgresql://postgres:123456@orders-db:5432/orders_db?schema=public
      - NATS_SERVERS=nats://nats-server:4222
    volumes:
      - ./orders-ms/src:/usr/src/app/src
    depends_on:
      - orders-db

  payments-ms:
    build: ./payments-ms
    ports:
      - "3003:3003"
    command: npm run start:dev
    environment:
      - PORT=3003
      - NATS_SERVERS=nats://nats-server:4222
      - BASE_URL=${PAYMENTS_MS_BASE_URL}
      - PAYPAL_BASE_URL=${PAYPAL_BASE_URL}
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_SECRET=${PAYPAL_SECRET}
    volumes:
      - ./payments-ms/src:/usr/src/app/src

  # 💿 Databases
  orders-db:
    image: postgres:16
    container_name: orders-db-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: orders_db
    ports:
      - "5432:5432"
    volumes:
      - ./orders-ms/postgres_data:/var/lib/postgresql/data

  db-mongo-users:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27018:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
